version: '3.1'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        ports:
          - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}

    managerdb:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8083:80
        environment:
            - PMA_ARBITRARY=1
        links:
            - db